externalIngress:
  labels:
    group: com.stakater.platform
    provider: stakater
    version: 0.12.0
  namespace: external-ingress
  image:
    name: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
    tag: 0.12.0
    pullPolicy: Always
  deployment:
    replicas: 2
    revisionHistoryLimit: 3
    criticalPod: "true"
    annotationsPrefix: ingress.kubernetes.io
  service:
    sslCert: arn:aws:acm:us-west-2:449074299682:certificate/b4d21f5a-0ef8-417e-b39d-30e9f6c50820
